name: Test ls.bat on Windows

on:
  push:
    paths:
      - 'ls.bat'
      - '.github/workflows/test-ls.yml'
  workflow_dispatch:

jobs:
  test-ls-bat:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Add repository root to PATH
        run: |
          echo $env:GITHUB_WORKSPACE\ls.bat >> $env:GITHUB_PATH
        shell: pwsh
      
      - name: Run ls.bat with -a flag
        run: |
          echo Testing -a flag
          .\ls.bat -a
        shell: cmd
      

      - name: Validate output contains file list
        run: |
          $output = & cmd /c " .\ls.bat -a"
          if ($output -notmatch "Directory of") {
              Write-Error "ls.bat did not output expected directory listing"
              exit 1
          }