name: Test ls.bat on Windows

on:
  push:
    paths:
      - 'ls.bat'
      - '.github/workflows/test-ls.yml'
  workflow_dispatch:

jobs:
  test-ls-bat:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Add repository root to PATH
        run: |
          echo $env:GITHUB_WORKSPACE\ls.bat >> $env:GITHUB_PATH
        shell: pwsh
      
      - name: Run ls.bat with -a flag
        run: |
          echo Testing -a flag
          .\ls.bat -a
        shell: cmd
      

      - name: Validate output contains file list
        run: |
          cmd /c "ls -a > output.txt"
          set /p output=<output.txt
          echo %output%
          set "escapedOutput=%output%"
          .\doesItContain.bat "!escapedOutput!" "Directory of"
        shell: cmd